# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 389b4d33c8b5c9b8c839a64d6df0b7068a04b888568d6f94bcf7d1c514de6b300ba44aab4c0dbde8e754c1db95c13496e1a993cec16209b62202748aabe9fed0

test:
  secret_key_base: 966e9c6c603bd068317d7d84d05c4e08de02a31fda15506ce9faa9380a59f2f6b37365ae396ee53606a1cf24a0c0e00e4ebf43715088bbd087dc2d228bf32181

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
